language: php

php:
  - 5.5
  - 5.6
  - nightly

install: composer install

script: composer build

after_script: php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#honeeybee"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
